config/routes.rb
require 'api_constraints'

Oncall::Application.routes.draw do
  resources :manual_oncall_schedule_approvals do
    member do
      get :approve
      get :reject
    end
  end
  resources :manual_oncall_schedules
  resource :calendars
  resources :oncall_schedules
  resource :user, only: [:show]


  devise_for :users, :controllers => { :registrations => 'registrations', :confirmations => 'confirmations', :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    put '/confirm' => 'confirmations#confirm'
  end

  root to: 'calendars#show'


  namespace :admin do
    match '/' => 'admin#index'
    resources :users,  :controllers => { :users => 'admin/users'}
  end

  resource :api, :controller => 'api/api' do
    get :current_version
    get :versions
  end
  namespace :api, :defaults => {:format => :json} do
    #API
    api_routes = lambda {
      resources :oncall_schedules
      resource :calendars do
        collection do
          get :current_on_call
          get :month_on_call_schedule
          get :on_call_users_by_date_range
        end
      end
    }

    scope module: :v1, constraints: APIConstraints.new(version: 1, default: true) do
      api_routes.call
    end
  end
end

app/models/oncall_schedule.rb
class OncallSchedule < ActiveRecord::Base
  attr_accessible :end_date, :start_date, :oncall_profiles, :oncall_profiles_attributes,
                  :mailing_list, :weeks, :name, :oncall_start_time, :oncall_start_day

  validates :end_date, presence: true, :unless => :weeks
  validates :start_date, presence: true
  validates :name, presence: true, :uniqueness => true
  validates :oncall_start_time, presence: true
  validates :oncall_start_day, presence: true

  belongs_to :scheduler, :class_name => 'User', :foreign_key => 'scheduler_id'
  has_many :calendars
  has_many :oncall_profiles
  belongs_to :last_notification_sent_to, :class_name => 'User', :foreign_key => 'last_notification_sent_to'
  has_many :manual_oncall_schedules
  has_many :users, :through => :oncall_profiles

  accepts_nested_attributes_for :oncall_profiles, :allow_destroy => true

  before_destroy :destroy_profiles
  before_save :mailing_list_to_array

  serialize :mailing_list

  def scheduled_users
    self.oncall_profiles.select { |p| p.oncall_position }.map{|p| p.user if p.oncall_position}
  end

  def profiles_to_schedule
    profiles = []

    start_week = self.start_date.beginning_of_week(start_day = self.oncall_start_day.downcase.to_sym)
    end_week = start_week + 1.weeks

    weeks_to_process = self.weeks ? self.weeks : (self.end_date.beginning_of_week - self.start_date.beginning_of_week(start_day = self.oncall_start_day.downcase.to_sym))/1.week

    valid_profiles = self.oncall_profiles.select { |p| p.oncall_position }
    sorted_profiles = valid_profiles.sort! { |x, y| x.oncall_position <=> y.oncall_position }
    weeks_to_process.to_int.times do
      sorted_profiles.each do |profile|
        break if profile.oncall_position.nil?

        if self.weeks
          break if start_week >= self.start_date.beginning_of_week(start_day = self.oncall_start_day.downcase.to_sym) + self.weeks.weeks
        else
          break if start_week > self.end_date.beginning_of_week
        end

        profiles << { :oncall_profile => profile, :start_date => start_week, :end_date => (end_week - 1.day) }

        start_week = end_week
        end_week = start_week + 1.weeks
      end
    end

    profiles
  end

  def users_between_dates(start_date, end_date)
    profiles = profiles_to_schedule

    valid_users = Array.new

    profiles.each do |p|
      valid_start = start_date.to_datetime.between? p[:start_date], p[:end_date]
      valid_stop = end_date.to_datetime.between? p[:start_date], p[:end_date]

      valid_users << p if valid_start || valid_stop
    end

    valid_users
  end

  def month_on_call
    profiles = self.profiles_to_schedule

    start_of_month = Date.today.beginning_of_month
    end_of_month = Date.today.end_of_month
    valid_profiles = Array.new
    profiles.each do |profile|
      if (start_of_month..end_of_month).cover?(Date.parse(profile[:start_date].time.strftime('%Y/%m/%d')))
        valid_profiles << profile
      end
    end

    valid_profiles
  end

  def current_on_call
    profiles = self.profiles_to_schedule

    start_of_week = Time.zone.now.beginning_of_week(self.oncall_start_day.downcase.to_sym)
    end_of_week = Time.zone.now.end_of_week

    start_of_last_week = (Time.zone.now - 6.days).beginning_of_week(self.oncall_start_day.downcase.to_sym)
    end_of_last_week = start_of_week
    profiles.each do |profile|
      if (start_of_week..end_of_week).cover?(profile[:start_date])
        now = Time.now.in_time_zone
        day_numbers = Hash[Date::DAYNAMES.map.with_index.to_a]
        scheduled_day = day_numbers[self.oncall_start_day]
        now_day = now.wday

        if (now_day == scheduled_day && now.strftime( "%H%M%S%N" ) >= self.oncall_start_time.in_time_zone.strftime( "%H%M%S%N" )) ||  now_day > scheduled_day
          return profile[:oncall_profile]
        end
      end
    end

    profiles.each do |profile|
      if (start_of_last_week..end_of_last_week).cover?(profile[:start_date])# && (start_of_last_week..end_of_last_week).cover?(profile[:end_date])
        return profile[:oncall_profile]
      end
    end

    nil
  end

  def notify_on_call(force = false)
    on_call = self.current_on_call.user

    if (self.last_notification_sent_to != on_call || force) || self.oncall_profiles.count == 1
      OncallScheduleNotifier.delay.on_call_reminder(on_call) if on_call.notifications?(:oncall_reminder_email)
      OncallScheduleNotifier.delay.on_call_reminder_pager(on_call) if on_call.notifications?(:oncall_reminder_pager)

      self.last_notification_sent_to = on_call
      self.save!
    end
  end

  def notify_all_on_call(force = false)
    if self.send_notify? || force
      on_call = Calendar.get_calendar.overwrite_user
      on_call ||= self.current_on_call.user

      self.oncall_profiles.each do |profile|
        OncallScheduleNotifier.delay.on_call_all_reminder(profile.user, on_call) if profile.user.notifications?(:oncall_reminder_email)
      end

      self.mailing_list.each do |email|
        OncallScheduleNotifier.delay.on_call_reminder_mailing_list(email, on_call)
      end

      self.last_notification_sent_to = on_call
      self.save!
    end
  end

  def send_notify?
    on_call = self.current_on_call.user
    self.last_notification_sent_to != on_call || self.oncall_profiles.count == 1
  end

  def send_monthly_notify?
    today = Date.today

    self.last_monthly_notification_sent_at.nil? ||
        (self.last_monthly_notification_sent_at.month < today.month && self.last_monthly_notification_sent_at.year <= today.year)
  end

  def notify_all_monthly_on_call
    on_calls = self.month_on_call

    if self.oncall_profiles.count > 0
      self.oncall_profiles.each do |profile|
        OncallScheduleNotifier.delay.on_call_monthly(profile.user, on_calls) if profile.user.notifications?(:oncall_monthly)
      end

      self.mailing_list.each do |email|
        OncallScheduleNotifier.delay.on_call_monthly_mailing_list(email, on_calls)
      end

      self.last_monthly_notification_sent_at = Date.today

      self.save
    end
  end

  private
  def destroy_profiles
    self.oncall_profiles.each do |profile|
      profile.destroy
    end
  end

  def mailing_list_to_array
    if self.mailing_list.is_a? String
      self.mailing_list = self.mailing_list.split("\r\n")
      self.mailing_list.each do |email|
        email.strip
      end
    end
  end
end

app/controllers/api/v1/oncall_schedules_controller.rb
class API::V1::OncallSchedulesController < ApplicationController
  def index
    @oncall_schedules = OncallSchedule.all
  end

  def show
    @oncall_schedule = OncallSchedule.find(params[:id])
  end
end

app/controllers/oncall_schedules_controller.rb
class OncallSchedulesController < ApplicationController
  load_and_authorize_resource

  # GET /oncall_schedules
  def index
    @oncall_schedules = OncallSchedule.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /oncall_schedules/1
  def show
    @oncall_schedule = OncallSchedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /oncall_schedules/new
  def new
    @oncall_schedule = create_profiles OncallSchedule.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /oncall_schedules/1/edit
  def edit
    @oncall_schedule = create_profiles OncallSchedule.find(params[:id])
  end

  # POST /oncall_schedules
  def create
    @oncall_schedule = OncallSchedule.new(params[:oncall_schedule])
    @oncall_schedule.scheduler = current_user

    respond_to do |format|
      if @oncall_schedule.save
        format.html { redirect_to @oncall_schedule, notice: 'Oncall schedule was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /oncall_schedules/1
  def update
    @oncall_schedule = OncallSchedule.find(params[:id])
    profiles = @oncall_schedule.oncall_profiles

    respond_to do |format|
      if @oncall_schedule.update_attributes(params[:oncall_schedule])
        format.html { redirect_to @oncall_schedule, notice: 'Oncall schedule was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /oncall_schedules/1
  def destroy
    @oncall_schedule = OncallSchedule.find(params[:id])
    @oncall_schedule.destroy

    respond_to do |format|
      format.html { redirect_to oncall_schedules_url }
    end
  end

  private
  def create_profiles(oncall_schedule)
    profiles = []
    User.all.each do |user|
      next if !user.has_role?(:user)

      if oncall_schedule.id
        current = OncallProfile.find_by_user_id_and_oncall_schedule_id user.id, oncall_schedule.id
        next if current
      end


      profile = OncallProfile.new(
          :user => user,
          :oncall_schedule => oncall_schedule
      )
      profiles << profile
    end

    oncall_schedule.oncall_profiles << profiles
    oncall_schedule
  end
end

app/helpers/oncall_schedules_helper.rb
module OncallSchedulesHelper
end

app/views/oncall_schedules/_form.html.erb
<%= form_for(@oncall_schedule) do |f| %>
    <% if @oncall_schedule.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@oncall_schedule.errors.count, "error") %> prohibited this oncall_schedule from being saved:</h2>

          <ul>
            <% @oncall_schedule.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :start_date %><br />
      <%= f.datetime_select :start_date %>
    </div>

    <div class="field" id="oncall_schedule_end_date">
      <%= f.label :end_date %><br />
      <%= f.datetime_select :end_date %>
    </div>

    <div class="field">
      <%= f.label :weeks %><br />
      <%= f.number_field :weeks %>
    </div>

    <div class="field">
      <%= f.label :oncall_start_time %><br />
      <%= f.time_select :oncall_start_time %>
    </div>

    <div class="field">
      <%= f.label :oncall_start_day %><br />
      <%= f.select :oncall_start_day, Date::DAYNAMES %>
    </div>

    <div>
      <h3><%= t('oncall_profile.users') %>:</h3>
      <%= f.fields_for :oncall_profiles do |oncall_profile_fields| %>
          <div class="field">
            <%= oncall_profile_fields.label :user %><br />
            <%= oncall_profile_fields.object.user.email %>
            <%= oncall_profile_fields.hidden_field :user_id, :value => oncall_profile_fields.object.user.id %>
          </div>
          <div class="field" id="oncall_profiles_position_user_<%= oncall_profile_fields.object.user.id %>">
            <%= oncall_profile_fields.label :oncall_position %><br />
            <%= oncall_profile_fields.select :oncall_position, (1..(User.select { |x| x.has_role?(:user) }).count), { include_blank: true } %>
          </div>
      <% end %>
    </div>

    <h3><%= t('oncall_schedule.notifications') %>:</h3>
    <div class="field">
      <%= f.label :mailing_list %><br />
      <%= f.text_area :mailing_list, :value => (@oncall_schedule.mailing_list ? (@oncall_schedule.mailing_list.kind_of?(Array) ? @oncall_schedule.mailing_list.join("\r\n") : @oncall_schedule.mailing_list) : '') %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/oncall_schedules/edit.html.erb
<h1><%= t('general.editing') % t('oncall_schedule.name') %></h1>

<%= render 'form' %>

<%= link_to 'Back', oncall_schedules_path %>

app/views/oncall_schedules/index.html.erb
<h1><%= t('general.listing') % t('oncall_schedule.name') %>
  <% if can? :create, OncallSchedule %>
    <span class='actions'>
      <%= link_to t('general.new'), new_oncall_schedule_path, :id => 'new_on_call_schedule_link' %>
    </span>
  <% end %>
</h1>

<div>
<table id='oncall_schedules_table' class='data_table'>
  <thead>
  <tr>
    <th><%= t('oncall_schedule.name_name') %></th>
    <th><%= t('oncall_schedule.start_date') %></th>
    <th><%= t('oncall_schedule.end_date') %></th>
    <th><%= t('oncall_schedule.weeks') %></th>
    <th><%= t('general.actions') %></th>
  </tr>
  </thead>

  <tbody>
  <% @oncall_schedules.each do |oncall_schedule| %>
  <tr>
    <td><%= link_to oncall_schedule.name, oncall_schedule %></td>
    <td><%= oncall_schedule.start_date %></td>
    <td><%= oncall_schedule.end_date %></td>
    <td><%= oncall_schedule.weeks %></td>
    <td>
      <%= link_to 'Edit', edit_oncall_schedule_path(oncall_schedule) %>
      <%= link_to 'Destroy', oncall_schedule, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/oncall_schedules/new.html.erb
<h1><%= "#{t('general.new')} #{t('oncall_schedule.name')}" %></h1>

<%= render 'form' %>

<%= link_to 'Back', oncall_schedules_path %>

app/views/oncall_schedules/show.html.erb
<h1><%= t('oncall_schedule.name') %></h1>

<p>
  <b><%= t('oncall_schedule.name_name') %>:</b>
  <%= @oncall_schedule.name %>
</p>

<p>
  <b><%= t('oncall_schedule.start_date') %>:</b>
  <%= @oncall_schedule.start_date.strftime(t('general.timestamp_to_str')) %>
</p>

<% if @oncall_schedule.weeks %>
<p>
  <b><%= t('oncall_schedule.weeks') %>:</b>
  <%=  @oncall_schedule.weeks %>
</p>
<% else %>
<p>
  <b><%= t('oncall_schedule.end_date') %>:</b>
  <%= @oncall_schedule.end_date.strftime(t('general.timestamp_to_str')) %>
</p>
<% end %>
<p>
  <b><%= t('oncall_schedule.oncall_start') %>:</b>
  <%= "#{@oncall_schedule.oncall_start_day.capitalize.pluralize} at #{@oncall_schedule.oncall_start_time.strftime(t('general.time_to_str'))}" %>
</p>
<p>
  <b><%= t('oncall_schedule.scheduler') %>:</b>
  <%= @oncall_schedule.scheduler.email %>
</p>
<br />
<h3><%= t('oncall_profile.users') %>:</h3>
<div class="table">
  <table cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered" id="oncall_schedules_table">
    <thead>
    <tr>
      <th><%= t('oncall_profile.user') %></th>
      <th><%= t('oncall_profile.position') %></th>
    </tr>
    </thead>

    <tbody>
    <% @oncall_schedule.oncall_profiles.each do |profile| %>
        <tr>
          <td><%= profile.user.email %></td>
          <td><%= profile.oncall_position %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<br />
<br />
<%= link_to 'Edit', edit_oncall_schedule_path(@oncall_schedule) %> |
<%= link_to 'Back', oncall_schedules_path %>