config/routes.rb
require 'api_constraints'

Oncall::Application.routes.draw do
  resources :manual_oncall_schedule_approvals do
    member do
      get :approve
      get :reject
    end
  end
  resources :manual_oncall_schedules
  resource :calendars
  resources :oncall_schedules
  resource :user, only: [:show]


  devise_for :users, :controllers => { :registrations => 'registrations', :confirmations => 'confirmations', :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    put '/confirm' => 'confirmations#confirm'
  end

  root to: 'calendars#show'


  namespace :admin do
    match '/' => 'admin#index'
    resources :users,  :controllers => { :users => 'admin/users'}
  end

  resource :api, :controller => 'api/api' do
    get :current_version
    get :versions
  end
  namespace :api, :defaults => {:format => :json} do
    #API
    api_routes = lambda {
      resources :oncall_schedules
      resource :calendars do
        collection do
          get :current_on_call
          get :month_on_call_schedule
          get :on_call_users_by_date_range
        end
      end
    }

    scope module: :v1, constraints: APIConstraints.new(version: 1, default: true) do
      api_routes.call
    end
  end
end

app/views/menus/_admin.html.erb
<li><%= link_to t('admin.administration'), admin_path %></li>

app/views/menus/_footer.html.erb
<div id="footer_menu">
<ul>
  <% unless user_signed_in? && User.omniauth_providers && User.omniauth_providers.include?(:auth_man) %>
  <li><%= link_to t('users.local_login'), new_user_session_path %></li>
  <% end %>
</ul>
</div>

app/views/menus/_menu.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to t('application.name'), root_path, :class => 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= t('menu.manage') %> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <% if current_user.has_role?(:user) %>
                    <li><%= link_to t('manual_oncall_schedule.request_overrides'), manual_oncall_schedules_path unless current_page?(manual_oncall_schedules_path) %></li>
                <% end %>
                <% if current_user.has_role?(:scheduler) %>
                    <% if current_user.has_role?(:user) && !current_page?(manual_oncall_schedules_path) %>
                        <li class="divider"></li>
                    <% end %>
                    <li><%= link_to t('calendar.calendar'), edit_calendars_path unless current_page?(edit_calendars_path)%></li>
                    <li><%= link_to t('oncall_schedule.schedules'), oncall_schedules_path unless current_page?(oncall_schedules_path)%></li>
                <% end %>
              </ul>
            </li>
        <% if current_user.has_role?(:admin) %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= t('admin.administration') %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= render 'menus/admin' %></li>
          </ul>
        </li>
        <% end %>
        <li class="divider-vertical"></li>
        <%= render 'menus/my_account', :app_config => APP_CONFIG, :user => current_user, :my_account_path => user_path, :gravatar_url => current_user.gravatar_url(:size => 20) %>
        <% else %>
          <% if User.omniauth_providers && User.omniauth_providers.include?(:auth_man) %>
            <li><%= link_to(t('users.login'), user_omniauth_authorize_path(:auth_man)) %></li>
         <% else %>
            <li><%= link_to(t('users.login'), new_user_session_path) %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>