config/routes.rb
require 'api_constraints'

Oncall::Application.routes.draw do
  resources :manual_oncall_schedule_approvals do
    member do
      get :approve
      get :reject
    end
  end
  resources :manual_oncall_schedules
  resource :calendars
  resources :oncall_schedules
  resource :user, only: [:show]


  devise_for :users, :controllers => { :registrations => 'registrations', :confirmations => 'confirmations', :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    put '/confirm' => 'confirmations#confirm'
  end

  root to: 'calendars#show'


  namespace :admin do
    match '/' => 'admin#index'
    resources :users,  :controllers => { :users => 'admin/users'}
  end

  resource :api, :controller => 'api/api' do
    get :current_version
    get :versions
  end
  namespace :api, :defaults => {:format => :json} do
    #API
    api_routes = lambda {
      resources :oncall_schedules
      resource :calendars do
        collection do
          get :current_on_call
          get :month_on_call_schedule
          get :on_call_users_by_date_range
        end
      end
    }

    scope module: :v1, constraints: APIConstraints.new(version: 1, default: true) do
      api_routes.call
    end
  end
end

app/models/manual_oncall_schedule.rb
class ManualOncallSchedule < ActiveRecord::Base
  attr_accessible :created_by, :end_date, :oncall_schedule_id, :oncall_user_id, :overridden_on_call_user_id, :start_date, :approval

  belongs_to :oncall_user, :foreign_key => :oncall_user_id, :class_name => 'User'
  belongs_to :overridden_on_call_user, :foreign_key => :overridden_on_call_user_id, :class_name => 'User'
  belongs_to :created_by, :foreign_key => :created_by, :class_name => 'User'
  belongs_to :oncall_schedule

  has_one :approval, :class_name => ManualOncallScheduleApproval, :foreign_key => :manual_oncall_schedule_id, :dependent => :delete

  validate :validate_manual_oncall_schedule
  validate :valid_dates
  validate :valid_override_users

  after_create :create_approval
  before_save :flatten_override_user

  def self.get_manual_oncall_schedule(date, oncall_schedule)
    manual_schedule = nil

    oncall_schedule.manual_oncall_schedules.each do |schedule|
      next unless date.between?(schedule.start_date, schedule.end_date)

      manual_schedule = schedule if schedule.valid_schedule?
    end

    manual_schedule
  end

  def valid_schedule?
    self.approval.approved?
  end

  private
  def valid_manual_oncall_schedule?
    start_manual_schedule = ManualOncallSchedule.get_manual_oncall_schedule self.start_date, self.oncall_schedule
    end_manual_schedule = ManualOncallSchedule.get_manual_oncall_schedule self.end_date, self.oncall_schedule

    if (start_manual_schedule && end_manual_schedule) && (start_manual_schedule.approval.rejected? && end_manual_schedule.approval.rejected?)
      true
    elsif start_manual_schedule.nil? && end_manual_schedule.nil?
      true
    else
      false
    end
  end

  def validate_manual_oncall_schedule
    errors.add(:manual_oncall_schedule, "is invalid. The start or end date you have entered is between a start and end date of an existing override.") unless valid_manual_oncall_schedule?
  end

  def valid_dates
    if self.start_date <= self.end_date
      true
    else
      errors.add(:manual_oncall_schedule, "is invalid. The start date must come before the end date.")
      false
    end
  end

  def create_approval
    self.approval ||= ManualOncallScheduleApproval.new(:oncall_user_approval => true)
  end

  def valid_override_users
    valid_users = self.oncall_schedule.users_between_dates(self.start_date, self.end_date)

    if valid_users.empty?
      errors.add(:manual_oncall_schedule, "date range is invalid. The date range you chose does not fall within anyone's scheduled on call duties.")
      false
    else
      if valid_users.count == 1
        if valid_users.first[:oncall_profile].user == self.oncall_user
          errors.add(:manual_oncall_schedule, "date range is invalid. You are attempting to override yourself.")
          false
        else
          true
        end
      elsif valid_users.count > 1
        errors.add(:manual_oncall_schedule, "date range is invalid. This override would affect more than one user, you can only override one users schedule at a time..")
        false
      end
    end
  end

  def flatten_override_user
    self.overridden_on_call_user = self.oncall_schedule.users_between_dates(self.start_date, self.end_date).first[:oncall_profile].user
  end
end

app/controllers/admin/manual_oncall_schedules_controller.rb
class Admin::ManualOncallSchedulesController < ApplicationController
  # GET /manual_oncall_schedules
  # GET /manual_oncall_schedules.json
  def index
    @manual_oncall_schedules = ManualOncallSchedule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @manual_oncall_schedules }
    end
  end

  # GET /manual_oncall_schedules/1
  # GET /manual_oncall_schedules/1.json
  def show
    @manual_oncall_schedule = ManualOncallSchedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @manual_oncall_schedule }
    end
  end

  # GET /manual_oncall_schedules/new
  # GET /manual_oncall_schedules/new.json
  def new
    @manual_oncall_schedule = ManualOncallSchedule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @manual_oncall_schedule }
    end
  end

  # GET /manual_oncall_schedules/1/edit
  def edit
    @manual_oncall_schedule = ManualOncallSchedule.find(params[:id])
  end

  # POST /manual_oncall_schedules
  # POST /manual_oncall_schedules.json
  def create
    @manual_oncall_schedule = ManualOncallSchedule.new(params[:manual_oncall_schedule])
    @manual_oncall_schedule.created_by = current_user

    respond_to do |format|
      if @manual_oncall_schedule.save
        format.html { redirect_to @manual_oncall_schedule, notice: 'Manual oncall schedule was successfully created.' }
        format.json { render json: @manual_oncall_schedule, status: :created, location: @manual_oncall_schedule }
      else
        format.html { render action: "new" }
        format.json { render json: @manual_oncall_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /manual_oncall_schedules/1
  # PUT /manual_oncall_schedules/1.json
  def update
    @manual_oncall_schedule = ManualOncallSchedule.find(params[:id])

    respond_to do |format|
      if @manual_oncall_schedule.update_attributes(params[:manual_oncall_schedule])
        format.html { redirect_to @manual_oncall_schedule, notice: 'Manual oncall schedule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @manual_oncall_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manual_oncall_schedules/1
  # DELETE /manual_oncall_schedules/1.json
  def destroy
    @manual_oncall_schedule = ManualOncallSchedule.find(params[:id])
    @manual_oncall_schedule.destroy

    respond_to do |format|
      format.html { redirect_to manual_oncall_schedules_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/manual_oncall_schedules_controller.rb
class ManualOncallSchedulesController < ApplicationController
  load_and_authorize_resource

  # GET /manual_oncall_schedules
  def index
    if current_user.has_role? :scheduler
      @manual_oncall_schedules = ManualOncallSchedule.all
    else
      @manual_oncall_schedules.where({oncall_user_id: current_user.id, overridden_on_call_user_id: current_user.id })
      @manual_oncall_schedules ||= Array.new
    end

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /manual_oncall_schedules/1
  def show
    @manual_oncall_schedule = ManualOncallSchedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /manual_oncall_schedules/new
  def new
    @manual_oncall_schedule = ManualOncallSchedule.new
    @oncall_schedule = Calendar.get_calendar.oncall_schedule

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # POST /manual_oncall_schedules
  def create
    @oncall_schedule = Calendar.get_calendar.oncall_schedule
    @manual_oncall_schedule = ManualOncallSchedule.new(params[:manual_oncall_schedule])

    @manual_oncall_schedule.created_by = current_user
    @manual_oncall_schedule.oncall_user_id = current_user.id
    @manual_oncall_schedule.oncall_schedule = Calendar.get_calendar.oncall_schedule

    respond_to do |format|
      if @manual_oncall_schedule.save
        format.html { redirect_to @manual_oncall_schedule, notice: 'Manual oncall schedule was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # DELETE /manual_oncall_schedule/1
  def destroy
    @manual_oncall_schedule = ManualOncallSchedule.find(params[:id])
    @manual_oncall_schedule.destroy

    respond_to do |format|
      format.html { redirect_to manual_oncall_schedule_url }
    end
  end
end

app/helpers/manual_oncall_schedules_helper.rb
module ManualOncallSchedulesHelper
  def on_call_schedule_users (oncall_schedule)
    oncall_schedule.scheduled_users.select { |u| u != current_user }
  end

  def approval_status (manual_schedule)
    if manual_schedule.approval.admin_rejected?
      t('manual_oncall_schedule_approvals.admin_rejected')
    elsif manual_schedule.approval.admin_approved?
        t('manual_oncall_schedule_approvals.admin_approved')
    elsif manual_schedule.approval.rejected?
      t('manual_oncall_schedule_approvals.rejected')
    else
      manual_schedule.approval.approved? ? t('manual_oncall_schedule_approvals.approved') : t('manual_oncall_schedule_approvals.pending_approval')
    end
  end

  def can_approve_reject(manual_oncall_schedule_approval)
    if current_user == manual_oncall_schedule_approval.manual_oncall_schedule.overridden_on_call_user || (current_user.has_role?(:scheduler) && current_user != manual_oncall_schedule_approval.manual_oncall_schedule.oncall_user)
      true
    else
      false
    end
  end

  def show_approve_link (manual_schedule)
    if manual_schedule.approval.approved?
      show_link = false
    else
      if current_user.has_role? :scheduler
        show_link = true
      elsif current_user.has_role?(:user) && current_user == manual_schedule.overridden_on_call_user
        if manual_schedule.approval.rejected? || manual_schedule.approval.approved?
          show_link = false
        else
          show_link = true
        end
      else
        show_link = false
      end
    end

    show_link
  end

  def show_reject_link (manual_schedule)
    if manual_schedule.approval.rejected?
      show_link = false
    else
      if current_user.has_role? :scheduler
        show_link = true
      elsif current_user.has_role?(:user) && current_user == manual_schedule.overridden_on_call_user
        if manual_schedule.approval.rejected? || manual_schedule.approval.approved?
          show_link = false
        else
          show_link = true
        end
      else
        show_link = false
      end
    end

    show_link
  end
end

app/views/manual_oncall_schedules/_form.html.erb
<%= form_for(@manual_oncall_schedule) do |f| %>
  <% if @manual_oncall_schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manual_oncall_schedule.errors.count, "error") %> prohibited this manual_oncall_schedule from being saved:</h2>

      <ul>
      <% @manual_oncall_schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date, {:start_year => Date.today.year} %>
  </div>

  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date, {:start_year => Date.today.year} %>
  </div>

  <div class="field">
    <%= label_tag t('manual_oncall_schedule.send_request_to') %><br />
    <%= text_field_tag :overridden_on_call_user, '', {:readonly => true, :style => 'border: 0;'} %>
  </div>

  <div class="actions">
    <%= f.submit t('manual_oncall_schedule.request_override') %>
  </div>
<% end %>

app/views/manual_oncall_schedules/index.html.erb
<h1><%= t('general.listing') % t('manual_oncall_schedule.overrides') %>
  <% if can? :create, ManualOncallSchedule %>
    <span class='actions'>
      <%= link_to t('general.new'), new_manual_oncall_schedule_path, :id => 'new_manual_oncall_schedule_link' %>
    </span>
  <% end %></h1>

<div>
  <table id='oncall_schedules_table' class='data_table'>
  <thead>
  <tr>
    <th><%= "Requesting User" %></th>
    <th><%= "Overridden User" %></th>
    <th><%= "Start Date" %></th>
    <th><%= "End Date" %></th>
    <th><%= "Approval Status" %></th>
    <th><%= t('general.actions') %></th>
  </tr>
  </thead>

  <tbody>
  <% @manual_oncall_schedules.each do |manual_oncall_schedule| %>
  <% next unless manual_oncall_schedule.overridden_on_call_user && manual_oncall_schedule.oncall_user %>
  <tr>
    <td><%= manual_oncall_schedule.oncall_user.name %></td>
    <td><%= manual_oncall_schedule.overridden_on_call_user.name %></td>
    <td><%= manual_oncall_schedule.start_date %></td>
    <td><%= manual_oncall_schedule.end_date %></td>
    <td><%= approval_status(manual_oncall_schedule) %></td>
    <td>
      <%= link_to t('general.show'), manual_oncall_schedule %>
      <%= link_to t('manual_oncall_schedule_approvals.approve'), approve_manual_oncall_schedule_approval_path(manual_oncall_schedule.approval.id, :redirect_to => manual_oncall_schedules_path) if show_approve_link manual_oncall_schedule %>
      <%= link_to t('manual_oncall_schedule_approvals.reject'), reject_manual_oncall_schedule_approval_path(manual_oncall_schedule.approval, :redirect_to => manual_oncall_schedules_path) if show_reject_link manual_oncall_schedule %>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/manual_oncall_schedules/new.html.erb
<h1><%= t('manual_oncall_schedule.request_override') %></h1>

<%= render 'form' %>

<%= link_to 'Back', manual_oncall_schedules_path %>

app/views/manual_oncall_schedules/show.html.erb
<h1><%= t('manual_oncall_schedule.show') % [@manual_oncall_schedule.start_date, @manual_oncall_schedule.end_date] %></h1>

<p>
  <b>Requesting User:</b>
  <%= @manual_oncall_schedule.oncall_user.name %>
</p>

<p>
  <b>Overridden on call user:</b>
  <%= @manual_oncall_schedule.overridden_on_call_user.name %>
</p>
<div>
  <h3>Approval Information:</h3>
  <ul style="list-style: none;">
    <li><b>Status:</b> <%= approval_status(@manual_oncall_schedule) %></li>
    <li><b>Action:</b>
    <% if can_approve_reject(@manual_oncall_schedule.approval) && (show_approve_link(@manual_oncall_schedule) || show_reject_link(@manual_oncall_schedule)) %>
      <%= link_to t('manual_oncall_schedule_approvals.approve'), approve_manual_oncall_schedule_approval_path(@manual_oncall_schedule.approval.id) if show_approve_link @manual_oncall_schedule %>
      <%= link_to t('manual_oncall_schedule_approvals.reject'), reject_manual_oncall_schedule_approval_path(@manual_oncall_schedule.approval) if show_reject_link @manual_oncall_schedule %>
    <% else %>
      <%= t('general.unavailable') %>
    <% end %>
    </li>
  </ul>
</div>
<br />
<br />
<%= link_to 'Edit', edit_manual_oncall_schedule_path(@manual_oncall_schedule) %> |
<%= link_to 'Back', manual_oncall_schedules_path %>