config/routes.rb
require 'api_constraints'

Oncall::Application.routes.draw do
  resources :manual_oncall_schedule_approvals do
    member do
      get :approve
      get :reject
    end
  end
  resources :manual_oncall_schedules
  resource :calendars
  resources :oncall_schedules
  resource :user, only: [:show]


  devise_for :users, :controllers => { :registrations => 'registrations', :confirmations => 'confirmations', :omniauth_callbacks => 'users/omniauth_callbacks' }
  devise_scope :user do
    put '/confirm' => 'confirmations#confirm'
  end

  root to: 'calendars#show'


  namespace :admin do
    match '/' => 'admin#index'
    resources :users,  :controllers => { :users => 'admin/users'}
  end

  resource :api, :controller => 'api/api' do
    get :current_version
    get :versions
  end
  namespace :api, :defaults => {:format => :json} do
    #API
    api_routes = lambda {
      resources :oncall_schedules
      resource :calendars do
        collection do
          get :current_on_call
          get :month_on_call_schedule
          get :on_call_users_by_date_range
        end
      end
    }

    scope module: :v1, constraints: APIConstraints.new(version: 1, default: true) do
      api_routes.call
    end
  end
end

app/models/user.rb
require 'role_model'

class User < ActiveRecord::Base
  include Gravtastic
  gravtastic :secure => false

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :async

  devise :omniauthable, :omniauth_providers => [:auth_man]

  include RoleModel

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :time_zone, :roles, :roles_mask, :fname, :lname, :pager_address,
                  :notify, :notifications

  # optionally set the integer attribute to store the roles in,
  # :roles_mask is the default
  roles_attribute :roles_mask

  # declare the valid roles -- do not change the order if you add more
  # roles later, always append them at the end!
  roles :admin, :scheduler, :user

  bitmask :notifications, :as => [:oncall_reminder_email, :oncall_reminder_pager, :oncall_monthly]

  has_many :oncall_profiles
  has_many :oncall_schedules, through: :oncall_profiles
  has_many :manual_oncall_schedules
  has_many :manual_oncall_schedule_approvals
  has_one :calendar

  validates :fname, :presence => true
  validates :lname, :presence => true
  validates :pager_address, :presence => true

  before_destroy :destroy_profiles

  def password_required?
    super if confirmed?
  end

  def password_match?
    self.errors[:password] << "can't be blank" if password.blank?
    self.errors[:password_confirmation] << "can't be blank" if password_confirmation.blank?
    self.errors[:password_confirmation] << "does not match password" if password != password_confirmation
    password == password_confirmation && !password.blank?
  end

  def full_name
    self.fname && self.lname ? "#{self.fname} #{self.lname}" : nil
  end

  def full_name_comma
    self.fname && self.lname ? "#{self.lname}, #{self.fname}" : nil
  end

  def name
    self.fname && self.lname ? "#{self.fname} #{self.lname}" : self.email
  end

  def self.from_omniauth(auth)
    user_return = where(provider: auth.provider, uid: auth.uid).first

    unless user_return
      user = User.find_by_email(auth.info['email'])

      user ||= User.new(
          :email        => auth.info.email,
          :password     => Devise.friendly_token[0,20],
          :fname        => auth.info.fname,
          :lname        => auth.info.lname,
          :time_zone    => auth.info.time_zone,
      )

      user.pager_address ||= '5555555555@vtext.com'
      user.uid      = auth.uid
      user.provider = auth.provider

      user.skip_confirmation!
      user.save

      user_return = user
    end

    user_return.sync_with_omniauth(auth)

    user_return
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.auth_man_data'] && session['devise.auth_man_data']['extra']['raw_info']
        user.email      = data['email'] if user.email.blank?
        user.fname      = data['fname'] if user.fname.blank?
        user.lname      = data['lname'] if user.lname.blank?
        user.time_zone  = data['time_zone'] if user.time_zone.blank?
      end
    end
  end

  def sync_with_omniauth(auth)
    unless self.confirmed?
      self.skip_confirmation!

      self.save
    end

    unless auth.info.fname == self.fname && auth.info.lname == self.lname && auth.info.time_zone == self.time_zone
      self.fname      = auth.info.fname
      self.lname      = auth.info.lname
      self.time_zone  = auth.info.time_zone

      self.save
    end
  end

  private
  def destroy_profiles
    self.oncall_profiles.each do |profile|
      profile.destroy
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def new
    @user = User.new
    @roles = User.valid_roles
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = t('admin.users.created_user')
      redirect_to admin_users_path
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
    @roles = @user.roles
  end

  def update
    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password].blank? and params[:user][:password_confirmation].blank?

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_user_path, notice: t('admin.users.updated_user') }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user == @user
      flash[:alert] = t('admin.users.cannot_delete')
    elsif @user.destroy
      flash[:notice] = t('admin.users.deleted_user')
    end

    respond_to do |format|
      format.html { redirect_to admin_users_path }
      format.json { head :no_content }
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def auth_man
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      session['devise_omniauth_myaccount'] = request.env['omniauth.auth'].info.my_account
      session['devise_omniauth_enable_gravatar'] = request.env['omniauth.auth'].info.enable_gravatar
      session['devise_login_type'] = :omniauth

      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => 'AuthMan') if is_navigational_format?
    else
      raise Exception.new('Failed to create or find user.')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_filter :set_user

  def show
  end

  private
  def set_user
    @user = current_user
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@user, :url => admin_users_path) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, :autofocus => true %>
    </div>
    <div class="field">
      <%= f.label :fname %><br />
      <%= f.text_field :fname %>
    </div>
    <div class="field">
      <%= f.label :lname %><br />
      <%= f.text_field :lname %>
    </div>
    <div class="field">
      <%= f.label :pager_address %><br />
      <%= f.text_field :pager_address %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="field">
      <%= f.label :roles %>
      <ul>
          <% @roles.each do |role| %>
              <li><%= role %><%= check_box_tag 'user[roles][]', role, @user.roles.include?(role) %></li>
          <% end %>
      </ul>
    </div>
    <div class="actions">
      <%= f.submit t('admin.users.send_confirmation_instructions') %>
    </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1><%= t('general.edit') % @user.email.upcase %></h1>

<%= form_for(@user, :url => admin_user_path) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :email %><br />
      <%= @user.email %>
    </div>
    <div class="field">
      <%= f.label :fname %><br />
      <%= f.text_field :fname %>
    </div>
    <div class="field">
      <%= f.label :lname %><br />
      <%= f.text_field :lname %>
    </div>
    <div class="field">
      <%= f.label :pager_address %><br />
      <%= f.text_field :pager_address %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </div>
    <div class="field">
      <%= f.label :roles %>
      <ul>
        <% User.valid_roles.each do |role| %>
            <li><%= role %><%= check_box_tag 'user[roles][]', role, @user.roles.include?(role) %></li>
        <% end %>
      </ul>
    </div>
    <div class="actions">
      <%= f.submit t('general.updated') %>
    </div>
<% end %>
<%= link_to t('general.back'), admin_users_path %>

app/views/admin/users/index.html.erb
<h1><%= t('general.listing') % t('user.users') %>
    <span class='actions'>
      <%= link_to t('general.new'), new_admin_user_path, :id => 'new_admin_user_link' %>
    </span>
</h1>
<div>
  <table id='admin_users_table' class='data_table'>
    <thead>
      <tr>
        <th><%= t('admin.users.email_address') %></th>
        <th><%= t('user.first_name') %></th>
        <th><%= t('user.last_name') %></th>
        <th><%= t('admin.users.created') %></th>
        <th><%= t('admin.users.last_login') %></th>
        <th><%= t('general.actions') %></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr id="user_<%= user.id %>">
            <td><%= link_to user.email, admin_user_path(user) %></td>
            <td><%= user.fname %></td>
            <td><%= user.lname %></td>
            <td><%= user.created_at.strftime(t('general.timestamp_to_str')) %></td>
            <td><%= user.last_sign_in_at ? user.last_sign_in_at.strftime(t('general.timestamp_to_str')) : t('general.not_applicable') %></td>
            <td>
                <%= link_to t('general.edit'), edit_admin_user_path(user) %>
                <% if current_user != user %>
                <%= link_to t('general.delete'), admin_user_path(user), :confirm => t('general.are_you_sure'), :method => :delete %>
                <% end %>
            </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/new.html.erb
<h1><%= "#{t('general.new')} #{t('user.user')}" %></h1>

<%= form_for(@user, :url => admin_users_path) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, :autofocus => true %>
    </div>
    <div class="field">
      <%= f.label :fname %><br />
      <%= f.text_field :fname %>
    </div>
    <div class="field">
      <%= f.label :lname %><br />
      <%= f.text_field :lname %>
    </div>
    <div class="field">
      <%= f.label :pager_address %><br />
      <%= f.text_field :pager_address %>
    </div>
    <div class="field">
      <%= f.label :roles %>
      <ul>
        <% User.valid_roles.each do |role| %>
            <li><%= role %><%= check_box_tag 'user[roles][]', role, @user.roles.include?(role) %></li>
        <% end %>
      </ul>
    </div>
    <div class="actions">
      <%= f.submit t('admin.users.send_confirmation_instructions') %>
    </div>
<% end %>

<%= link_to t('general.back'), admin_users_path %>

app/views/admin/users/show.html.erb
<h1><%= @user.email.upcase %></h1>

<p>
  <b><%= t('user.first_name') %>:</b>
  <%= @user.fname %>
</p>

<p>
  <b><%= t('user.last_name') %>:</b>
  <%= @user.lname %>
</p>

<p>
  <b><%= t('user.pager_address') %>:</b>
  <%= @user.pager_address %>
</p>

<p>
  <b><%= t('admin.users.login_count') %>:</b>
  <%= @user.sign_in_count %>
</p>

<p>
  <b><%= t('admin.users.last_ip') %>:</b>
  <%= @user.last_sign_in_ip %>
</p>

<p>
  <b><%= t('admin.users.confirmed_on') %>:</b>
  <%= @user.confirmed_at %>
</p>

<p>
  <b><%= t('admin.users.confirmation_sent') %>:</b>
  <%= @user.confirmation_sent_at %>
</p>

<p>
  <b><%= t('admin.users.unconfirmed') %>:</b>
  <%= @user.unconfirmed_email %>
</p>

<p>
  <b><%= t('admin.users.failed_attempts') %>:</b>
  <%= @user.failed_attempts %>
</p>

<p>
  <b><%= t('general.created_on') %>:</b>
  <%= @user.created_at %>
</p>

<p>
  <b><%= t('general.updated_on') %>:</b>
  <%= @user.updated_at %>
</p>

<p>
  <b><%= t('user.roles') %>:</b>
  <ul class="roles">
      <% @user.roles.each do |r| %>
      <li><%= r %></li>
      <% end %>
  </ul>
</p>

<br />
<br />
<%= link_to t('general.edit'), edit_admin_user_path(@user) %> |
<%= link_to t('general.back'), admin_users_path %>